### ISSUE TITLE
[commands() & findCommand()] [Subcategory Require functions grab from da-slash src node_module location]

### ISSUE THREAD

**Issue by fasko-web** [xlyr-on/da-slash#6]
**Describe the bug**
When using the categories option it requires command files from da-slash's node_modules directory, instead of the location the module is required at. IE. Commands are in './commands/folders/' but it's looking for them in './node_modules/da-slash/src/commands/folders/'

### commands() & findCommand(command_name)
```js
// ./bot.js

config = {
  commands: {
    directory: './commands',
    subcategories: 'true'
  }
}

// ./node_modules/da-slash/src/client.js

9  | async commands() {
21 |   let command = require(`${dir}/${folder}/${file}`);

37 | async findCommand(command_name) {
49 |   let command = require(`${dir}/${subfolderRef}/${file}`);
```

The error being produced
`UnhandledPromiseRejectionWarning: Error: Cannot find module './commands/subcategory/command.js'`

**Expected behavior**
Expected to find existing module at specified location.

**Additional context**
Adding `require.main.require();` to line 21 and 49 in client.js fixed the issue for me

**Comment by xlyr-on** [comment]
Thank you for opening up this issue.
I will probably publish the new patch this coming weekend. Do tell me about your concerns and if I did it correctly, as I'm new to Github and packages. Thank you!!

**Comment by fasko-web** [comment]
No problem! Still getting used to the two myself.
After playing around w/ the changes for a bit outside my current use case, `require.main` probably isn't the best solution either. 
If the file requiring da-slash isn't in the root directory, then it'll throw the original error again.
The easiest way I could figure out w/ how to handle it is requiring Node.js' Path module, and changing:
```js
const dir = this.config.commands.directory;
//        |
//        v
const dir = path.join(__dirname, '../../../', this.config.commands.directory);
```
Could probably be handled better since this assumes the location of node_modules is left unchanged, but works for majority of use-cases and allows for the rest of your files to be located anywhere, with the `config.commands.directory` always starting from the project's root folder.
